config/routes.rb
Rails.application.routes.draw do
    
  ActiveAdmin.routes(self)

    root to: 'home#index'

    devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "registrations" }
    

    post 'places/create_place_from_black_book' => 'places#create_place_from_black_book', as: :create_from_black_book
    
    resources :places, only: [:index, :show, :new, :create]

    resources :users, only: [:show, :edit, :update] do 
      resources :black_books, only: [:new, :create, :edit, :update]
      member do
            get :following, :followers
      end
    end

    resources :black_books, only: [:show, :index, :destroy] do
      resources :black_book_places, only: [:new, :create]
    end
    
    get 'black_books/search' => 'black_books#search', as: :search_black_books
    resources :black_book_places, only: [:show]
    resources :places, only: [:show, :index]
    resources :followships, only: [:create, :destroy]
    
    post 'black_book_places/update_position' => 'black_book_places#update_position'
    post 'black_book_places/:id/send_to_archive' => 'black_book_places#send_to_archive', as: :archive
    resources :black_book_places, only: [:edit, :update]
    
    post 'black_books/:id/upvote' => 'black_books#upvote', as: :upvote_black_book
    post 'black_books/:id/downvote' => 'black_books#downvote', as: :downvote_black_book
    get 'get_more_black_books' => 'black_books#get_more_black_books', as: :get_more_black_books
    get 'get_more_places' => 'places#get_more_places', as: :get_more_places

    get 'users/:id/get_more_followers' => 'users#get_more_followers', as: :get_more_followers
    get 'users/:id/get_more_followings' => 'users#get_more_followings', as: :get_more_followings
    
    get 'terms' => 'home#terms', as: :terms
    get 'about_us' => 'home#about_us', as: :about_us
    get 'help' => 'home#help', as: :help

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	after_action :get_social_friends, only: [:index]
	
	def index
		@black_book_pictures = %w(berlin los_angeles paris shanghai lisbon)
		@cities_pictures = %w(paris berlin san-francisco tokyo sydney cape-town)
	end

	def feed
		@user = current_user
		@black_books = BlackBook.friends(@user)
	end

	def terms
	end

	def about_us
	end

	def help
	end
	
	private
	
	def get_social_friends
		
		if user_signed_in?
			social_params = {}
			
			current_user.authorizations.find_each do |auth|
				get_params social_params, auth.provider
			end
			socialfriends = SocialFriends.new(social_params)
			
			if social_params[:facebook_token]
				fb_friends = socialfriends.get_facebook_friends 
				SocialFriendshipBuilder.perform_later current_user.id, fb_friends, 'Facebook'
			end	

			twitter_friends = socialfriends.get_twitter_friends if current_user.authorizations.where(provider: 'Twitter').first
			linkedin_connections = socialfriends.get_linkedin_connections if current_user.authorizations.where(provider: 'LinkedIn').first


		end

	end

	def get_params(social_params, auth)
		social_params["#{auth.downcase}_token".to_sym] = current_user.authorizations.where(provider: auth).first.token
		social_params["#{auth.downcase}_secret".to_sym] = current_user.authorizations.where(provider: auth).first.secret
		social_params["#{auth.downcase}_user_id".to_sym] = current_user.authorizations.where(provider: auth).first.uid.to_i
	end

end

app/views/home/about_us.html.slim
= content_for :title do
	title
		| fivemarks - about us
.container.padded-down
	.row.row-space-8
		.about-us.col-xs-12.col-sm-8.col-sm-offset-2
			h1 About fivemarks	
			
			h2 1. What is Fivemarks?
			p
				|Fivemarks allow you to share easily your black books and to discover amazing places curated by our community. Each black book contains a story, a cover pcture and up to 5 places. It allows you to discover cities through a limited number of places within a particular context.
			
			h2 2. But why only five places?
			p
				|Gathering informations about a city you've never been to is a pain. Travel guides, websites or blogs curate numerous great places, but there are just too much. 
			p	
				|Providing only a limited number of places within a context is, in our opinion, the best way to gather information in a usable and helpful way.
			
			h2 3. So why should I use fivemarks?
			p
				| Remember the last time a friend sked you about a city you've been to. You started making a nice ppt but you couldn't remember these amazing restaurant with these beautiful terrace and this small bar in the heart of the city...
			p 
				| With fivemarks this will smooth as hell. We are connected to foursquare and have acces to more than 30 million places around the world. And no need of a ppt, pdf, psd or any other acronyms, everything will be in your browser.
			
			h2 4. Can I give you insights and feedbacks.
			p
				|Sure, we are thrilled about that, just shout a mail at ideas@fivemarks.in with your ideas or suggestions. We'll try to get back to you asap.			
	.row
		.team.col-xs-12.col-sm-8.col-sm-offset-2
			.role.col-sm-6.col-xs-12
				.user-profile-pic.rounded
					= image_tag asset_url('thomas.jpg') 
				h1 Thomas
				h2 Founder
				p
					| I created fivemarks because I was tired of buying all these guides with so much adresses but without any context. I think places are as important as the people who choose it, this is why fivemarks is first about you.
			.role.col-sm-6.col-xs-12
				.user-profile-pic.rounded
					= image_tag asset_url('june_da_akita.jpg') 
				h1 June
				h2 Chief Woof Officer
				p
					|I'm in charge of being always hungry and a huge source of fluffyness.
				p 
					|My passions are eating, sleeping, playing with other dogs, then sleep...				

app/views/home/feed.html.slim
h1 Toto

app/views/home/help.html.slim
= content_for :title do
	title
		| fivemarks - help
.container.padded-down
	.row.row-space-8
		.help.col-xs-12.col-sm-8.col-sm-offset-2
			h1 Help
			h2 1. How can I create a black book?
			p
				|There ie nothing easier than this. You just have to click on the button at the top right of your screen on your laptop. If you're on your phone you need to open the menu tab and then click on the button.
			
			h3 a. Title
			p
				|The title helps adding context to your black book. This allows people to know more specifically what your black book is about.
			
			h3 b. Picture	
			p	
				|The picture will be used as the cover of your black book and adds a more personnal touch to it.
			
			h3 c. City	
			p	
				|Each black book is focused on a city, this is why you need to choose a city.
			
			h3 d. Story	
			p	
				|It allows you to tell the story of your trip. You can talk about your experience, the city or whatever you want.

				|You can talk about the places you've vissited and liked but this is NOT where you choose the places you add to your black book	
			h3 e. Adding places
			p
				|After creating the black book, you're redirected to a new page which allows to adding places.

			p
				|You can select up to five places. To add a place you just need to type its name and we'll find it for you. You can also add a small story about this place if you have anything to share.
			h2 2. The place I want to add doesn't exist
			
			p
				| Shout a mail to feedbacks@fivemarks.in. We'll sort it out!

			h2 3. How can I edit/delete a black book I created
			p 
				| You need to go to your profile. Then you will see all the black books you've created. Just click on the edit (or delete) button on the black book you want to edit (or delete).

			h2 4. How can I edit/delete a place I added to a black book.
			p 
				| When inside the edit page for your black book. Just click on the edit (or delete) button on the place you want to edit (or delete). You can't change the information about a particular place, just the story you wrote about	

			

app/views/home/index.html.slim
= content_for :title do
	title
		| Fivemarks - never miss a place you'll love
 	div.search-wrapper
 		div.landing-wrapper
 		div.search-container
 			div.va-container
 				.centering
 					h1 Never miss a place you'll love
 					h2 The easiest way to share your travel stories
 			.search-bar.col-xs-12.col-sm-6.col-sm-offset-3
 				.form-user
 					= simple_form_for(:search,  url: black_books_path, method: 'get', defaults: { input_html: { class: 'default_class' } }) do |f|			
 						input.user-account autocomplete="off" autofocus="false" name="search" placeholder="search a city..." type="text" id="user_input_autocomplete_address"
 						= f.button :submit, "Search", class: "btn-user-submit pink-button", name: nil

 	div.moto
 		div.container 
	 		div.row
	 			div.col-sm-4.col-xs-12.moto-containers
	 				= image_tag "backpack.svg", class:"moto-icon"
	 				h3 Travel smoothly, you won't have to bring a zillion city guides with you
	 			div.col-sm-4.col-xs-12.moto-containers
	 				= image_tag "map.svg", class:"moto-icon"
	 				h3 Walk in your friends footprints
	 			div.col-sm-4.col-xs-12.moto-containers
	 				= image_tag "bookmark.svg", class:"moto-icon"
	 				h3 Find the best place and bring some stories back
 	div.cut-quote
 		div.cut-cover
 			div.container.text-center
 			blockquote 
 				| "This place was cooler before it was cool" 
 				small A guy from Portland
 	div.home-section
 		div.container 
	 		div.row
	 			div.col-xs-12.col-sm-6
	 				.back-books
	 					.va-middle
	 						h1 One city, five places
	 			div.col-xs-12.col-sm-6
	 				div.back-books
		 				- @black_book_pictures.each_with_index do |city, index|
		 					= image_tag "#{city}.png"
	.cut-quote2	 					
	section.cities-ribbon
		- @cities_pictures.each_with_index do |city, index|
			div.col-lg-2.col-md-4.col-sm-12 
				= link_to black_books_path(search: "#{city}")
					div[class= "discovery-card #{city}-style"]
						.city-badge
							.iconmelon
							  svg viewbox=("0 0 32 32") 
							    use xlink:href="##{city}"
						.city-title
							h1 #{city}
	section.your-turn
		div.container
			- if current_user
				= link_to new_user_black_book_path(current_user), class: "btn btn-primary", id: "landing-btn" do
              		|  Create your guide
            - else
            	= link_to new_user_registration_path, class: "btn btn-primary", id: "landing-btn" do
              		|  Join us!  	

	= content_for :meta_facebook do
		meta property = "og:title" content= "Fivemarks"
		meta property = "og:image" content= "#{asset_url('logo_rounded.png')}"
		meta property = "og:url" content= "http://fivemarks.in"
		meta property = "og:description" content= "Fivemarks is the easiest way to create and share your travel stories"
		meta property = "og:site_name" content="fivemarks"

		meta name="twitter:card" content="summary_large_image"
		meta name="twitter:site" content="@fivemarks_in"
		meta name="twitter:title" content="Fivemarks - never miss a place you'll love"
		meta name="twitter:description" content="The easiest way to share your travel stories"
		meta name="twitter:image" content="#{asset_url('logo_rounded.png')}"

	= content_for :js do
		script src = "https://maps.googleapis.com/maps/api/js?libraries=places&amp;key=AIzaSyAhp6C4bGRbxb-fI9r69B-uocco11a9qjE"
		= javascript_include_tag "black_books/autocomplete.js"
		javascript: 
			window.sr = new scrollReveal();