config/routes.rb
Rails.application.routes.draw do
    
  ActiveAdmin.routes(self)

    root to: 'home#index'

    devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "registrations" }
    

    post 'places/create_place_from_black_book' => 'places#create_place_from_black_book', as: :create_from_black_book
    
    resources :places, only: [:index, :show, :new, :create]

    resources :users, only: [:show, :edit, :update] do 
      resources :black_books, only: [:new, :create, :edit, :update]
      member do
            get :following, :followers
      end
    end

    resources :black_books, only: [:show, :index, :destroy] do
      resources :black_book_places, only: [:new, :create]
    end
    
    get 'black_books/search' => 'black_books#search', as: :search_black_books
    resources :black_book_places, only: [:show]
    resources :places, only: [:show, :index]
    resources :followships, only: [:create, :destroy]
    
    post 'black_book_places/update_position' => 'black_book_places#update_position'
    post 'black_book_places/:id/send_to_archive' => 'black_book_places#send_to_archive', as: :archive
    resources :black_book_places, only: [:edit, :update]
    
    post 'black_books/:id/upvote' => 'black_books#upvote', as: :upvote_black_book
    post 'black_books/:id/downvote' => 'black_books#downvote', as: :downvote_black_book
    get 'get_more_black_books' => 'black_books#get_more_black_books', as: :get_more_black_books
    get 'get_more_places' => 'places#get_more_places', as: :get_more_places

    get 'users/:id/get_more_followers' => 'users#get_more_followers', as: :get_more_followers
    get 'users/:id/get_more_followings' => 'users#get_more_followings', as: :get_more_followings
    
    get 'terms' => 'home#terms', as: :terms
    get 'about_us' => 'home#about_us', as: :about_us
    get 'help' => 'home#help', as: :help

end

app/models/place.rb
class Place < ActiveRecord::Base
  extend FriendlyId
	has_many :black_book_places
	has_many :black_books, through: :black_book_places
  has_many :uploaded_files, as: :imageable
  has_and_belongs_to_many :categories, -> {uniq}
	after_create :set_foursquare_picture
  after_update :save_foursquare_picture,  if: :foursquare_picture_url_changed?
  
	accepts_nested_attributes_for :black_book_places, allow_destroy: true
  friendly_id :name, use: :history
	geocoded_by :address
  after_create :geocode, if: Proc.new {|c| c.latitude.nil? && c.longitude.nil?}

  scope :friends, ->(user) {
    joins(black_books: {user: :followers}).where("followships.follower_id = ?", user.id)
  }

  self.per_page = 6
  
  def update_score(new_rank)
    
    if (1..5).include? new_rank
      self.ranking = self.ranking.to_i + 1
    elsif new_rank == nil
      self.ranking = self.ranking.to_i - 1
    end

		self.save   	
  end
  
  def self.search_around(search_query)
    near(search_query)
  end

  def slug_candidates
    [
      :name,
      [:name, :city],
      [:name, :category, :city]
    ]
  end
  
  def should_generate_new_friendly_id?
    name_changed?  
  end
  
  protected
  	
	def set_foursquare_picture
		foursquare_additional_infos = FoursquareInfos.new(self).get_additional_infos()
		self.update(foursquare_additional_infos)
	end

  def save_foursquare_picture
    #FoursquarePicture.perform_later self.id
    
    # begin
    #   self.uploaded_files.new.file_from_url self.foursquare_picture_url 
    # rescue Exception => e
    #   p e.message
    #   self
    # end
  
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	respond_to :html, :js
	before_action :foursquare_place_params, only: [:create_place_from_black_book]
	before_action :place_params, only: [:create]
	before_action :set_place, only: [:show]
	
	rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

	def index

	end
	
	def show
		@geolocations = MapMarkersGenerator.new(@place).create_markers()
		@place_coordinates = [@place.latitude, @place.longitude]
		place_categories = @place.categories.map {|c| "%#{c.name}%"}
		@similar_places = Place.where("category ILIKE ANY ( array[:category] ) AND id != :id ", {category: place_categories, id: @place.id}).near([@place.latitude, @place.longitude]).where.not(foursquare_picture_url: nil).limit(6).order("RANDOM()")
		@active_black_books = BlackBook.includes(:user, :black_book_places).joins(:black_book_places).where("black_book_places.place_id = ? AND black_book_places.position IS NOT NULL", @place.id)

		@attributes = %w(address city category)

	end

	def new
		@place = Place.new()
		authorize @place
	end

	def create
		@place = Place.create(place_params)
		authorize @place
	end
	
	def create_place_from_black_book

		@place = Place.find_or_create_by(foursquare_id: @foursquare_place_params[:foursquare_id]) do |place|
			
			place.city = @foursquare_place_params[:city]
			place.zipcode = @foursquare_place_params[:zipcode]
			place.name = @foursquare_place_params[:name]
			place.address = @foursquare_place_params[:address] 
			place.latitude = @foursquare_place_params[:latitude]
			place.longitude = @foursquare_place_params[:longitude]
			place.category = @foursquare_place_params[:category]
			place.state = @foursquare_place_params[:state]
		
		end

		respond_to do |format|

      		if @place.persisted?
      			if @black_book_place = @place.black_book_places.find_by_black_book_id(@foursquare_place_params[:black_book_places_attributes]["0"][:black_book_id])
      			#@black_book_place = @place.black_book_places.where(black_book_id: @black_book_id).first
	      			if @black_book_place.position
		      			#format.html redirect_to edit_user_black_book_path(@black_book_place.black_book.user.id,@black_book_place.black_book.id)
		      			format.json { render json: 'no_new_place', status: :found }
		      			format.js   { render action: 'no_new_place', status: :found }
		      		else
		      			@black_book_place.update_attributes(@foursquare_place_params[:black_book_places_attributes]["0"])
		      			#format.html redirect_to edit_user_black_book_path(@black_book_place.black_book.user.id,@black_book_place.black_book.id)
		      			format.json { render json: 'retrieve_place', status: :found }
		      			format.js   { render action: 'retrieve_place', status: :found }
		      		end	
	      		else
	      			@black_book_place = @place.black_book_places.create(@foursquare_place_params[:black_book_places_attributes]["0"])
	      			format.html { redirect_to edit_user_black_book_path(@black_book_place.black_book.user.id,@black_book_place.black_book.id), notice: 'Place was successfully created.' }
	      			format.json { render json: 'create_new_place', status: :created, location: black_book_place(@black_book_place) }
	      			format.js   { render action: 'create_new_place', status: :created, locals: {place: @place, black_book_place: @black_book_place}}
      			end
      		else
      			format.html { render action: 'new' }
      			format.json { render json: @place.errors, status: :unprocessable_entity }
      			format.js   { render json: @place.errors, status: :unprocessable_entity }
      		end
      	end
	end

	def get_more_places

		if params[:search]
			@places = Place.near(params[:search], 10)
							.includes(:uploaded_files)
							.joins(:black_book_places)
							.where.not(black_book_places: {position: nil})
							.uniq
							.order('ranking desc')
							.paginate(:page => params[:page])
		end
		@attributes = %w(address city category)
		
		respond_to do |format|
			format.html
			format.js
		end	
	end	
	

	private

	def set_place
		begin
			@place = Place.includes(:uploaded_files, black_books: :user).friendly.find(params[:id])	
		rescue	
			@place = Place.includes(:uploaded_files, black_books: :user).find(params[:id])
		end	
	end

	def place_params
		params.require(:place).permit(:foursquare_id, :city, :zipcode, :name, :address, :category, :state, black_book_places_attributes: [:rank, :black_book_id])
	end

	def foursquare_place_params
		@foursquare_place_params = params.require(:place)
										.permit(:foursquare_id, :city, :zipcode, :name, :address, :latitude, :longitude, :category, :state, 
												black_book_places_attributes: [:position, :black_book_id, :place, :story, 
												uploaded_files_attributes: [:file]]
												)
	end

	def user_not_authorized
    	flash[:alert] = "You are not authorized to perform this action."
    	redirect_to(request.referrer || new_user_registration_path)
  	end
end

app/helpers/places_helper.rb
module PlacesHelper
	
	def render_price(place)
		if price = place.price
			price_tag = ''
			price.times {price_tag = price_tag + '<i class="fa fa-usd dollar-sign"></i>'}
			('<div class="attributes"><strong>Price: </strong><p class="text-truncate">' + price_tag + '</p><div class="clear"></div></div>').html_safe
		end
	end
end

app/views/places/_comment_block.html.slim
= render partial: './shared/user_credentials', locals: {user: user}
.black-book-place-story
	p Written on #{(black_book.created_at).strftime("%b %d")} by
	= link_to user
		| #{user.name || user.username}
	.places-story-wrapper	
		p #{black_book.story}
.comment-block-actions
	- if !signed_in?
		= render partial: './users/follow_unsigned'
	- elsif !current_user.following?(user) && !(current_user == user) 
		= render partial: './users/follow', locals: {followed: user}
.clear
hr					 	

app/views/places/_picture_wrapper.html.slim
.picture-wrapper
	.place-picture style=("background-image: url('#{picture}');")

app/views/places/_place_infos.html.slim
.place-main-data
	h1 #{place.name}
	.place-main-adress
		i.fa.fa-map-marker.fa-2x
		p #{place.address}
	h3 #{place.city}
.place-type.text-center
	.type-wrapper
		h1 #{place.category}
.place-attributes
	.col-xs-9
		- %w(twitter facebook_username formatted_phone).each_with_index do |attr,i|
			- if place[attr.to_sym]
				.attribute
					i.fa class="#{%w(fa-twitter fa-facebook-official fa-phone)[i]}"
					|    #{place[attr.to_sym]}
	.rating-wrapper.col-xs-3 style=("background-color: rgba(#{(255 * (1 - place.foursquare_rating.to_f/10)).to_i}, #{(255 * (place.foursquare_rating.to_f/10)).to_i}, 0, 0.7);")
		h1 #{place.foursquare_rating}

app/views/places/_related_black_books.html.slim
= render partial: './black_books/show_partials/black_book', locals: {black_book: black_book, caption: " has curated", owner: black_book.user, can_edit: can_edit}

								 	
				

app/views/places/create_new_place.js.erb
//$('#place_black_book_places_attributes_0_position').val() = parseInt($('#place_black_book_places_attributes_0_position').val()) + 1; 
if ($('#active-places-list > ul > li').last().length > 0) {
	$("<%= j render partial: 'black_books/show_place_edit', locals: {place: @place, black_book_place: @black_book_place, picture_url: @place.foursquare_picture_url, archive: false} %>").insertAfter($('#active-places-list > ul > li').last().fadeIn());
} else {
	$("<%= j render partial: 'black_books/show_place_edit', locals: {place: @place, black_book_place: @black_book_place, picture_url: @place.foursquare_picture_url, archive: false} %>").insertBefore($('#new-place').fadeIn());
}

if ($('#active-places-list > ul > li').length > 4) {
	$('#new-place').hide();
	$("<%= j render partial: 'black_books/black_book_full' %>").appendTo($('ul.place-list#sortable')).fadeIn();
};
$('#new-place-form').modal_success()

app/views/places/get_more_places.js.erb
$('#places').append("<%= j render partial: './black_books/resource_container', locals: {resources: @places} %>");

<% if @places.next_page %>
	$('.user-places').find('.pagination').replaceWith('<%= j will_paginate @places %>');
<% else %>
	$('.user-places').find('.see-more').remove();
<% end %>

app/views/places/index.html.slim
div.container.padded-down
	div.row
		div.col-xs-12.col-sm-4.col-sm-offset-4
			= form_tag places_path, class: "navbar-form navbar-left", :method => 'get' do
    			= text_field_tag :search, params[:search], class: "form-control"
    			= submit_tag "Search", :name => nil, class: "btn btn-primary"

app/views/places/new.html.slim
div.container.padded-down
	div.col-xs-12.col-sm-6.col-sm-offset-3
		h1 
			| Create a new Place
		= simple_form_for @place,
		url: url_for(action: 'create', controller: 'places'),
		method: 'post', 
		html: { class: "form-horizontal" }, wrapper: :horizontal_form do |f|
			.form-inputs
                  = f.input :name, required: true, input_html: {id: "name"}
                  = f.input :address, input_html: {id: "user_input_autocomplete_address"}
                  fieldset.disabled
                        = f.input :zipcode, disabled: true, input_html: {id: "postal_code"}
                        = f.input :city, disabled: true, input_html: {id: "locality"}
                        = f.input :state, disabled: true, input_html: {id: "administrative_area_level_1"}
                  = f.input :category, input_html: {id: "category"}
                  .form-actions
                  = f.button :submit, "Create", id: "create-place"

= content_for :js do

      script src = "https://maps.googleapis.com/maps/api/js?libraries=places&amp;key=AIzaSyAhp6C4bGRbxb-fI9r69B-uocco11a9qjE"
      = javascript_include_tag "black_books/autocomplete.js"

app/views/places/no_new_place.js.erb
alert("This place was is already in your guide");
if ( $('.place-list > li').length <= 5 ) {
	$('#new-place-form').fadeIn();
}

app/views/places/retrieve_place.js.erb
//$('#place_black_book_places_attributes_0_position').val() = parseInt($('#place_black_book_places_attributes_0_position').val()) + 1; 
$("<%= j render partial: 'black_books/show_place_edit', locals: {place: @place, black_book_place: @black_book_place, picture_url: @place.foursquare_picture_url, archive: false} %>").insertAfter($('#active-places-list > ul > li').last().fadeIn());

if ($('#active-places-list > ul > li').length > 4) {
	$('#new-place').hide();
	$("<%= j render partial: 'black_books/black_book_full' %>").appendTo($('ul.place-list#sortable')).fadeIn();
};
$('#new-place-form').modal_success();
$('#archived-places-list').find('.item').each( function () {
	if ($(this).data('itemId') == <%= @black_book_place.id %>) {
			$(this).remove();
	};
});

app/views/places/show.html.slim
= content_for :title do
	title
		| #{@place.name}

.page-wrapper	
	.container.padded-down
		.back-link
			=link_to black_books_path(params:{search: "#{@place.city}"})
				i.fa.fa-arrow-left
				| Explore #{@place.city}
		.place-main-wrapper.row-space-4
			.row
				.col-xs-12.col-md-7.col-lg-8
					- if @place.uploaded_files.count > 1
						= render partial: "./shared/carousel", locals: {pictures: @place.uploaded_files}
					- else 
						= render partial: "picture_wrapper", locals: {picture: @place.foursquare_picture_url}
				.col-xs-12.col-md-5.col-lg-4.text-center	
					= render partial: "place_infos", locals: {place: @place}
		= render partial: "./shared/foursquare_attribution" if @place.foursquare_id
		.place-user-info.col-xs-12.col-sm-8.col-sm-offset-2					
			h4 #{@active_black_books.count} people have added #{@place.name} to their black books
			hr 
			- @active_black_books.select{|b| b if b.black_book_places.first.story != nil &&  b.black_book_places.first.story != ''}.last(10).each do |black_book|
				.user-comment
					= render partial: 'comment_block', locals: {black_book: black_book.black_book_places.first, user: black_book.user}				

	.map-wrapper.map-place
		#map
	
	- if @similar_places.length > 0	
		.container.similar-places
			h1.strong.text-center.row-space-8 Similar places
			.places-list-wrapper#active-places-list
				ul.place-list.list-unstyled
					- @similar_places.each do |similar_place|	
						= render partial: './black_books/show_place', locals: {place: similar_place, black_book_place: similar_place, archive: false}
	
	
	- if @active_black_books.length > 0
		.container.active-city-guides
			h1.strong.text-center.row-space-8 Black books containing #{@place.name}
			places-list-wrapper#active-places-list
				ul.place-list.list-unstyled
					- @active_black_books.each do |black_book|
						.listing
							item.get-full-width.col-xs-12.col-sm-6.col-md-4.row-space-4
								= render partial: 'related_black_books', locals: {black_book: black_book, can_edit: false}					
- if !current_user
	= render './modals/disconnected_modal'
- if @voters	
	= render partial: './modals/user_list', locals: {users: @voters}
.md-overlay.transparent-white		
= content_tag(:div, id: "city-boundaries-coordinates", data: {url: @place_coordinates}) do
= content_tag(:div, id: "geolocations", data: {url: @geolocations}) do	

= content_for :meta_facebook do
	meta property = "og:title" content= "#{@place.name}"
	- if @place.uploaded_files != []
		meta property = "og:image" content= "#{@place.uploaded_files.last.file.url(:medium)}"
	- else
		meta property = "og:image" content= "#{asset_url('logo_rounded.png')}"	
	meta property = "og:url" content= "http://www.fivemarks.in/places/#{@place.slug}"
	meta property = "og:description" content= "#{@place.categories.map{|c| c.name}.join(', ')}"

	meta name="twitter:card" content = "summary_large_image"
	meta name="twitter:site" content = "@fivemarks_in"
	meta name="twitter:title" content = "#{@place.name}"
	meta name="twitter:description" content = "#{@place.categories.map{|c| c.name}.join(', ')}"
	- if @place.uploaded_files != []
		meta name="twitter:image" content = "#{@place.uploaded_files.last.file.url(:large)}"
	- else
		meta name="twitter:image" content = "#{asset_url('logo_rounded.png')}"
			

= content_for :js do
	script src = "https://api.tiles.mapbox.com/mapbox.js/v2.1.5/mapbox.js"
	= javascript_include_tag "classie"
	= javascript_include_tag "black_books/map"
	= javascript_include_tag "users/disconnected"												